# Site specific settings
title: "The d4rk h4ck"
name: "Website name"
keywords: "Security, Hacking"
author: "Sindhoor Tilak"
baseurl: ""
url: "https://sin9yt.net"
description: "sin9yt's personal blog"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
disqus: 
twitter: sin9yt
facebook: 
github: sin9yt
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
