# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "sin9yt"
tagline:          ":: Home"
description:      "...d4rk h4ck"
url:              "https://sin9yt.net"
baseurl:          "/"
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Sindhoor Tilak
  url:            https://twitter.com/sin9yt

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0

github:
  repo:             https://github.com/sin9yt/sin9yt.github.io
twitter: https://twitter.com/sin9yt